// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlyiP8YNlhiwjPUE7hL5ha0j1K7sH--bs',
    appId: '1:630270810691:android:e9c324a8ea8ce2f46d92f6',
    messagingSenderId: '630270810691',
    projectId: 'linca-4202a',
    storageBucket: 'linca-4202a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa97JpFA65mCHZ6OkvY4nTP8cIKLbVoqk',
    appId: '1:630270810691:ios:d93523d35c22dcb96d92f6',
    messagingSenderId: '630270810691',
    projectId: 'linca-4202a',
    storageBucket: 'linca-4202a.firebasestorage.app',
    androidClientId: '630270810691-o1qo7tid48c0rj66bga3gp787fgadqne.apps.googleusercontent.com',
    iosClientId: '630270810691-mo60isvre5hc52lu4p9rq548q0jf31d2.apps.googleusercontent.com',
    iosBundleId: 'com.fefeyo.linca',
  );

}