name: FVM Setup & Codegen
description: "Install Dart, setup FVM, cache SDKs, pub get, codegen, upload artifacts"
runs:
  using: "composite"
  steps:
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install FVM
      shell: bash
      run: |
        dart pub global activate fvm
        echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"
        echo "FVM_CACHE_PATH=$HOME/.fvm" >> "$GITHUB_ENV"

    - name: Cache FVM & Pub (restore)
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.FVM_CACHE_PATH }}
          ~/.pub-cache
        key: fvm-${{ runner.os }}-${{ hashFiles('.fvmrc') }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          fvm-${{ runner.os }}-${{ hashFiles('.fvmrc') }}-
          fvm-${{ runner.os }}-

    - name: Install Flutter via FVM
      shell: bash
      run: |
        fvm install
        fvm flutter --version

    - name: make init
      shell: bash
      run: make init

#    - name: Codegen (build_runner)
#      shell: bash
#      run: |
#        fvm flutter pub run build_runner build \
#          --delete-conflicting-outputs \
#          --build-filter "lib/**"

    - name: Upload codegen artifacts
      uses: actions/upload-artifact@v4
      with:
        name: codegen-${{ github.sha }}
        if-no-files-found: error
        path: |
          lib/**/*.g.dart
          lib/**/*.freezed.dart
          lib/**/*.gr.dart
          lib/**/*.gen.dart
          lib/**/generated/**
          build/**
