name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup & init
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: cache fvm
        uses: ./fvm-setup

  build:
    name: Flutter Build
    needs: setup
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'pull_request' &&
       github.event.action == 'closed' &&
       github.event.pull_request.merged == true &&
       github.event.pull_request.base.ref == 'develop')
      || (github.event_name == 'push' && github.ref == 'refs/heads/develop')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: cache fvm
        uses: ./fvm-setup

      - name: Run init
        run: make init

      - name: Run build apk
        run: fvm flutter build apk

  analyze:
    name: Flutter Analyze
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: cache fvm
        uses: ./fvm-setup

      - name: Run init
        run: make init

      - name: Run Analyze
        run: make analyze

  test:
    name: Flutter test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: cache fvm
        uses: ./fvm-setup

      - name: Run init
        run: make init

      - name: Run test
        run: make test
